# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-22 14:12
from __future__ import unicode_literals

from django.db import migrations


from data_api.sql_views.operations import RawSQLMigration

migrator = RawSQLMigration(('data_api', 'sql_views', 'sql_templates'), {})

class Migration(migrations.Migration):

    dependencies = [
        ('sql_views', '0001_initial'),
    ]

    operations = [
        migrator.get_migration('create_contact_view.sql'),
    ]
