# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-11 11:13
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='geometry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='staging.Geometry'),
        ),
    ]
