# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-11 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0003_auto_20180611_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignevent',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
