# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-11 13:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0005_auto_20180611_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staging.Group'),
        ),
    ]
