# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-20 12:51
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0010_auto_20180621_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowstart',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staging.Flow'),
        ),
        migrations.AlterField(
            model_name='flowstart',
            name='restart_participants',
            field=models.NullBooleanField(),
        ),
    ]
