# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-04 06:34
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Count


def clean_duplicates(apps, schema_editor):
    """
    Goes through the listed models and deletes all instances with a duplicate UUID except for
    the most recently created one.
    """
    uuid_models = [
        'Group',
        'Contact',
        'Channel',
        'Campaign',
        'Label',
        'Flow',
        'FlowStart',
        'CampaignEvent',

    ]

    for model_name in uuid_models:
        model_class = apps.get_model('staging', model_name)
        uuids_with_duplicates_qs = model_class.objects.values('uuid').annotate(Count('uuid')).filter(
            uuid__count__gt=1
        )
        uuids_with_duplicates = [row['uuid'] for row in uuids_with_duplicates_qs.all()]
        preserved_uuids = set()
        for model_instance in model_class.objects.filter(uuid__in=uuids_with_duplicates).order_by('-pk'):
            if model_instance.uuid in preserved_uuids:
                print('deleting {}: {} ({})'.format(model_name, model_instance, model_instance.pk))
                model_instance.delete()
            else:
                print('preserving {}: {} ({})'.format(model_name, model_instance, model_instance.pk))
                preserved_uuids.add(model_instance.uuid)


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0012_auto_20190703_1419'),
    ]

    operations = [
        migrations.RunPython(clean_duplicates, migrations.RunPython.noop),
    ]
