# Generated by Django 2.2.3 on 2019-07-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0014_auto_20190704_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='server',
            field=models.CharField(default='https://app.rapidpro.io/', max_length=100),
        ),
    ]
